# Generated by Django 6.0.6 on 2026-07-24 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon_class', models.CharField(blank=True, help_text='Standard icon name, e.g., wifi, parking, coffee', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='CoWorkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, help_text='URL of space thumbnail image', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='spaces', to='workspaces.amenity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('CABIN', 'Private Cabin'), ('DESK', 'Shared Desk'), ('MEETING', 'Meeting Room')], default='DESK', max_length=10)),
                ('seating_capacity', models.PositiveIntegerField(help_text='Number of persons this unit accommodates')),
                ('area_sqft', models.DecimalField(decimal_places=2, help_text='Area in square feet', max_digits=8)),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='workspaces.coworkingspace')),
            ],
        ),
    ]
